version: "3.7"
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
  db:
    image: "mysql/mysql-server:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: mobile_banking
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8081:80
    